[package]
name = "snapshot_srv"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "55.1.0"
arrow-flight = "55.1.0"
tonic = "0.13.1"
tokio = { version = "1", features = ["full"] }
prost = "0.13.5"
tokio-stream = "0.1.17"